:science:
    - icon-lightbulb
:recreation
    - icon-camera
:health
    - icon-stethoscope
:news and media
    - icon-bullhorn
:entertainment
    - icon-film
:education
    - icon-book
:government
    - icon-building
:computers and internet
    - icon-laptop
:business and economy
    - icon-money
:arts
    - icon-picture
:society and culture
    - icon-group
:social science
    - icon-signal
